In [1]:
import pandas as pd
df = pd.read_csv("../HeuristicModel/PossibleDataSets/india-districts-census-2011.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Columns: 118 entries, District code to Total_Power_Parity
dtypes: int64(116), object(2)
memory usage: 590.1+ KB

In [2]:
df.describe()

,District code,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,Male_SC,Female_SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
count,640.000000,6.400000e+02,6.400000e+02,6.400000e+02,6.400000e+02,6.400000e+02,6.400000e+02,6.400000e+02,6.400000e+02,6.400000e+02,...,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000
mean,320.500000,1.891961e+06,9.738598e+05,9.181011e+05,1.193186e+06,6.793182e+05,5.138675e+05,3.146537e+05,1.617739e+05,1.528798e+05,...,786.046875,1696.456250,294.000000,215.300000,509.300000,194.204688,261.245313,455.450000,279.631250,3315.412500
std,184.896367,1.544380e+06,8.007785e+05,7.449864e+05,1.068583e+06,5.924144e+05,4.801816e+05,3.129818e+05,1.611216e+05,1.520336e+05,...,1038.854733,1720.535151,638.345281,362.684243,968.538748,424.108001,587.279450,1007.364839,1050.934537,4638.568719
min,1.000000,8.004000e+03,4.414000e+03,3.590000e+03,4.436000e+03,2.614000e+03,1.822000e+03,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000
25%,160.750000,8.178610e+05,4.171682e+05,4.017458e+05,4.825982e+05,2.764365e+05,2.008920e+05,8.320850e+04,4.230700e+04,4.267175e+04,...,236.750000,589.000000,59.000000,24.750000,95.000000,19.000000,21.000000,44.000000,18.000000,1024.250000
50%,320.500000,1.557367e+06,7.986815e+05,7.589200e+05,9.573465e+05,5.483525e+05,4.038590e+05,2.460160e+05,1.255485e+05,1.178550e+05,...,518.000000,1220.500000,149.000000,118.500000,278.000000,84.000000,85.500000,186.500000,60.500000,2238.500000
75%,480.250000,2.583551e+06,1.338604e+06,1.264277e+06,1.602260e+06,9.188582e+05,6.641550e+05,4.477078e+05,2.284602e+05,2.140502e+05,...,941.250000,2233.250000,296.500000,262.000000,564.500000,213.250000,293.000000,497.000000,215.500000,3959.000000
max,640.000000,1.106015e+07,5.865078e+06,5.195070e+06,8.227161e+06,4.591396e+06,3.635765e+06,2.464032e+06,1.266504e+06,1.197528e+06,...,10334.000000,13819.000000,10835.000000,3595.000000,14430.000000,5027.000000,7597.000000,12624.000000,18289.000000,60163.000000

In [3]:
list(df.columns.values)

['District code',
 'State name',
 'District name',
 'Population',
 'Male',
 'Female',
 'Literate',
 'Male_Literate',
 'Female_Literate',
 'SC',
 'Male_SC',
 'Female_SC',
 'ST',
 'Male_ST',
 'Female_ST',
 'Workers',
 'Male_Workers',
 'Female_Workers',
 'Main_Workers',
 'Marginal_Workers',
 'Non_Workers',
 'Cultivator_Workers',
 'Agricultural_Workers',
 'Household_Workers',
 'Other_Workers',
 'Hindus',
 'Muslims',
 'Christians',
 'Sikhs',
 'Buddhists',
 'Jains',
 'Others_Religions',
 'Religion_Not_Stated',
 'LPG_or_PNG_Households',
 'Housholds_with_Electric_Lighting',
 'Households_with_Internet',
 'Households_with_Computer',
 'Rural_Households',
 'Urban_Households',
 'Households',
 'Below_Primary_Education',
 'Primary_Education',
 'Middle_Education',
 'Secondary_Education',
 'Higher_Education',
 'Graduate_Education',
 'Other_Education',
 'Literate_Education',
 'Illiterate_Education',
 'Total_Education',
 'Age_Group_0_29',
 'Age_Group_30_49',
 'Age_Group_50',
 'Age not stated',
 'Households_with_Bicycle',
 'Households_with_Car_Jeep_Van',
 'Households_with_Radio_Transistor',
 'Households_with_Scooter_Motorcycle_Moped',
 'Households_with_Telephone_Mobile_Phone_Landline_only',
 'Households_with_Telephone_Mobile_Phone_Mobile_only',
 'Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car',
 'Households_with_Television',
 'Households_with_Telephone_Mobile_Phone',
 'Households_with_Telephone_Mobile_Phone_Both',
 'Condition_of_occupied_census_houses_Dilapidated_Households',
 'Households_with_separate_kitchen_Cooking_inside_house',
 'Having_bathing_facility_Total_Households',
 'Having_latrine_facility_within_the_premises_Total_Households',
 'Ownership_Owned_Households',
 'Ownership_Rented_Households',
 'Type_of_bathing_facility_Enclosure_without_roof_Households',
 'Type_of_fuel_used_for_cooking_Any_other_Households',
 'Type_of_latrine_facility_Pit_latrine_Households',
 'Type_of_latrine_facility_Other_latrine_Households',
 'Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households',
 'Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households',
 'Not_having_bathing_facility_within_the_premises_Total_Households',
 'Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households',
 'Main_source_of_drinking_water_Un_covered_well_Households',
 'Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households',
 'Main_source_of_drinking_water_Spring_Households',
 'Main_source_of_drinking_water_River_Canal_Households',
 'Main_source_of_drinking_water_Other_sources_Households',
 'Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households',
 'Location_of_drinking_water_source_Near_the_premises_Households',
 'Location_of_drinking_water_source_Within_the_premises_Households',
 'Main_source_of_drinking_water_Tank_Pond_Lake_Households',
 'Main_source_of_drinking_water_Tapwater_Households',
 'Main_source_of_drinking_water_Tubewell_Borehole_Households',
 'Household_size_1_person_Households',
 'Household_size_2_persons_Households',
 'Household_size_1_to_2_persons',
 'Household_size_3_persons_Households',
 'Household_size_3_to_5_persons_Households',
 'Household_size_4_persons_Households',
 'Household_size_5_persons_Households',
 'Household_size_6_8_persons_Households',
 'Household_size_9_persons_and_above_Households',
 'Location_of_drinking_water_source_Away_Households',
 'Married_couples_1_Households',
 'Married_couples_2_Households',
 'Married_couples_3_Households',
 'Married_couples_3_or_more_Households',
 'Married_couples_4_Households',
 'Married_couples_5__Households',
 'Married_couples_None_Households',
 'Power_Parity_Less_than_Rs_45000',
 'Power_Parity_Rs_45000_90000',
 'Power_Parity_Rs_90000_150000',
 'Power_Parity_Rs_45000_150000',
 'Power_Parity_Rs_150000_240000',
 'Power_Parity_Rs_240000_330000',
 'Power_Parity_Rs_150000_330000',
 'Power_Parity_Rs_330000_425000',
 'Power_Parity_Rs_425000_545000',
 'Power_Parity_Rs_330000_545000',
 'Power_Parity_Above_Rs_545000',
 'Total_Power_Parity']